// AUTH USER
export const GET_AUTHUSER = 'GET_AUTHUSER';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const REGISTER_USER = 'REGISTER_USER';
// LOGIN MESSAGE
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const DEFAULT_MESSAGE = 'DEFAULT_MESSAGE';
// VEHELE
export const GET_ALL_VEHICLES = 'GET_ALL_VEHICLES';
export const EDIT_VEHICLE = 'EDIT_VEHICLE';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
// USERS
export const GET_USERS = 'GET_USERS';
export const USER_DEVICES = 'USER_DEVICES';
export const UNASSIGN_DEVICE = 'UNASSIGN_DEVICE';
export const ASSIGN_DEVICE = 'ASSIGN_DEVICE';
export const SEND_ADMIN_NOTIFICATION = 'SEND_ADMIN_NOTIFICATION';
// DEVICES
export const GET_DEVICES = 'GET_DEVICES';
export const ADD_DEVICE = 'ADD_DEVICE';
export const GET_UNASSIGN_DEVICE = 'GET_UNASSIGN_DEVICE';
// LOADING_DATA
export const LOADING_DATA = 'LOADING_DATA';
// POPUP MESSAGE
export const VEHICLE_UPDATE_SUCSS = 'VEHICLE_UPDATE_SUCSS';
export const VEHICLE_NOT_UPDATE = 'VEHICLE_NOT_UPDATE';
export const DEVICE_ADDED_SUCSS = 'DEVICE_ADDED_SUCSS';