// USER
export const GET_USER = 'GET_USER';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const REGISTER_USER = 'REGISTER_USER';
// VEHELE
export const GET_ALL_VEHICLES = 'GET_ALL_VEHICLES';
export const EDIT_VEHICLE = 'EDIT_VEHICLE';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
// MESSAGE
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const DEFAULT_MESSAGE = 'DEFAULT_MESSAGE';
// LOADING_DATA
export const LOADING_DATA = 'LOADING_DATA';
// POPUP MESSAGE
export const VEHICLE_UPDATE_SUCSS = 'VEHICLE_UPDATE_SUCSS';
export const VEHICLE_NOT_UPDATE = 'VEHICLE_NOT_UPDATE';